### ISSUE TITLE
Plex Easter Egg

### ISSUE THREAD

**Issue by PF94** [Craftplacer/TweakUtility#10]
**Describe the solution you'd like**
~Make it so in the options (the TweakUtility.exe.config file), if someone types "PF = 94", then the Plex theme should be set.~

In the credits, If someone types P, F, 9, 4, then the Plex theme should be set. It's somewhat similar to the Konami Code Easter Egg in the about window.

**Comment by PF94** [comment]
Should this be putted in the "TU 1.1" milestone?

**Comment by Craftplacer** [comment]
I dunno, the theme engine is really just intended for making the app feel more belonging to the right Windows version.

**Comment by PF94** [comment]
Well this easter egg was just meant to reference the themes that were started to be deprecated after Build 94 was released.

**Comment by Craftplacer** [comment]
Yeah I thought of adding dark mode but in the end it just seemed to complicate things more
