### ISSUE TITLE
A pretty minor and useless "Revenge" easter egg.

### ISSUE THREAD

**Issue by PF94** [Craftplacer/TweakUtility#16]
Creeper.
Aw man.
So we back in the github repo.
and now i'm doing this request.

Maybe just a small comment in the source code or something else. I dunno :P

**Comment by Craftplacer** [comment]
You can get creative with this and add an easter egg so that this time it will be interactive for the end user instead of devs looking into the source.

**Comment by PF94** [comment]
What happens if someone searches "Creeper". it should show only one result. being "Aw man".

then clicking "Aw man" should show the entire lyrics, the original ones, not the "cringy" MLG 2016 one that was added by a random person.

**Comment by Craftplacer** [comment]
seems doable, but to be fair, let's consider that you have to set the time for this to work, to one get less criticism that this meme is old (therefore the time), and two to give the user a bit more effort.

**Comment by PF94** [comment]
it'll prob be unnoticed until some minecraft fanboy in the future searches minecraft mobs on TU for no reason.

**Comment by PF94** [comment]
I've built Build 99 and it now has this easter egg, now waiting that it gets closed along with the other stuff on this milestone.
