### ISSUE TITLE
Any Windows XP support? (Installer Bug)

### ISSUE THREAD

**Issue by Nojus2001** [Craftplacer/TweakUtility#18]
After wanting to try this interesting software, i have noticed that it requires .NET Framework 4.6.1 that isn't supported on XP:
![image](https://user-images.githubusercontent.com/47254156/62534996-ff34f300-b852-11e9-98a4-f7b38ac9c60e.png)
Sooo, my question is, will there be any backwards compatibility with the program in the near future? :)

**Comment by Craftplacer** [comment]
This program actually was designed for .NET Framework 4, this might've just me shipping out a wrong setting. This will be fixed in beta 1.1.0

**Comment by Craftplacer** [comment]
Actually if I think about it, it's the installers fault, it had the latest .NET Framework version preset. I set it back.

**Comment by PF94** [comment]
The installer is pretty much brand new, It may have some mistakes (such as the framework that Craftplacer said earlier).

**Comment by PF94** [comment]
I could fix it, but #23 blocks me from doing it

**Comment by Craftplacer** [comment]
> I could fix it, but #23 blocks me from doing it

I already fixed it. as mentioned in here

> I set it back.
