### ISSUE TITLE
Display Properties - Change the name of the current unsaved theme.

### ISSUE THREAD

**Issue by PF94** [Craftplacer/TweakUtility#2]
**Registry keys**
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\LastTheme]
"DisplayName of Modified"="Windows XP (Modified)"

**Mininum Windows Version**
Windows XP

**Maximum Windows Version**
Windows XP

**Sources and/or information**
This changes the name of the unsaved, modified theme. Meaning that a name of a modified theme can be changed without saving the theme.

**Comment by PF94** [comment]
I love how nobody cares about this :P

**Comment by PF94** [comment]
This is a old idea that nobody has cared about... Let's hope it gets added on the 1.1.xx builds :P

**Comment by Craftplacer** [comment]
I can't see where it would and be practical

**Comment by PF94** [comment]
Some people want to rename their unsaved themes without saving it

**Comment by Craftplacer** [comment]
I mean it will be obviously deprioitzed by me, since I can't see it fitting with other options.
If you want however, you can add it yourself.

**Comment by PF94** [comment]
Wow, finally.

:tada:

**Comment by Craftplacer** [comment]
![image](https://user-images.githubusercontent.com/22963120/62690905-e13fcd80-b9cd-11e9-97de-9224827fb6f3.png)
This is not functional.

**Comment by PF94** [comment]
Damnit. I'll invalid this but i'll keep it open just IF i find another registry value... I'd need the ReactOS registry editor...

**Comment by PF94** [comment]
moving it to not started..

**Comment by Craftplacer** [comment]
Seems that the issue doesn't seem to get re-implemented so I'll close this
