### ISSUE TITLE
MSN Plus Scripts via listview

### ISSUE THREAD

**Issue by PF94** [Craftplacer/TweakUtility#21]
Originally made as a note by @AlienFuture

**Comment by Craftplacer** [comment]
@AlienFuture When did we say that this is going to be a feature?

**Comment by AlienFuture** [comment]
2 days ago maybe?

**Comment by PF94** [comment]
I'm kinda curious, can i have the screenshot of the DMs about the MSN+ Scripts idea?

**Comment by AlienFuture** [comment]
we talked in vs with //
anyways what is the wrong with it?

**Comment by Craftplacer** [comment]
I can remember you suggesting this to be a feature but I mentioned it wouldn't fit Tweak Utility, for being out of scope.

**Comment by PF94** [comment]
I was almost going to add "wontfix", aka "wont implement"...

I dunno about this... But TU isn't meant as a full customizer for MSN Messenger.

**Comment by Craftplacer** [comment]
>But TU isn't meant as a full customizer for MSN Messenger.
This. Including an entire library of MSN scripts will give MSN messenger way too much focus and exceed the focus of Tweak Utility.

This might be better put into Escargot or MSN Love (if we still want to work on that).

If nobody has to say anything further I'll close this as wontfix.

**Comment by AlienFuture** [comment]
So i suggested this idea in VS to create a scripts subpage in TU. You said this is so earlier theres more important things to make/finish. So ya, thats why I put this idea into low piority list to make. Today I mentioned what about Newtonsoft then you said no you dont wanna but xml we can.

Yea not a full MSN customizer but i would make msn customizer too because i think theres a Msn Messenger page and i wanna make Scripts subpage. 

So again, whats the wrong with it?

**Comment by PF94** [comment]
> This might be better put into Escargot or MSN Love (if we still want to work on that).

I don't think MSN Love is developed anymore... I haven't heard news about it since early-2019 or even late-2018.

**Comment by Craftplacer** [comment]
> i think theres a Msn Messenger page and i wanna make Scripts subpage.

Yeah but we don't have the platform for this, I don't want this to become a hub to download and install stuff

> I don't think MSN Love is developed anymore... I haven't heard news about it since early-2019 or even late-2018.

Balazs and I had plans to maybe revive it, but both haven't continued working on it, I pitched to walkingphasers about integrating a MSN extras hub into Escargot's website.

**Comment by AlienFuture** [comment]
The separated application for scripts nobody will use i can bet it, thats why, why not put into tu. It doesn't bother anyone to more code lines but then forgot this...........................................

**Comment by PF94** [comment]
So i settled on adding "invalid" and "wont fix", which i'll rename to "won't be implemented" shortly.
