### ISSUE TITLE
The TweakUtility Installer Source Code does not seem to load properly on Visual Studio 2017.

### ISSUE THREAD

**Issue by PF94** [Craftplacer/TweakUtility#23]
**Describe the bug**
A error prompt shows whenever loading the Source Code of the application, It says that the Installer is not compatible with VS17.

The error, on the HTML file the app generated... says:
> TweakUtility.Installer\TweakUtility.Installer.vdproj: The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660751&projecttype=54435603-DBB4-11D2-8724-00A0C9A8B90C

The link basically shows me a old outdated post from 2013, around the time Visual Studio 2013 was released.

**To Reproduce**
1. Run Visual Studio 2017
2. Load the source code from Git

**Expected behavior**
It should load properly.

**Screenshots**

**Information (please complete the following information):**
 - OS: Windows 8.1
 - Version 0.1.99

**Additional context**

**Comment by Craftplacer** [comment]
It's not a bug, please look into what it requires.
[Microsoft Visual Studio Installer Projects](https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects)

**Comment by PF94** [comment]
I removed the "won't be implemented" label because it isn't a feature request.
