### ISSUE TITLE
Internet Explorer - Change the ABOUT: urls of Blank, The New Tabs Page, Navigation Errors, etc.

### ISSUE THREAD

**Issue by PF94** [Craftplacer/TweakUtility#3]
**Registry keys**
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\AboutURLs]
"blank"="res://mshtml.dll/blank.htm"
"DesktopItemNavigationFailure"="res://ieframe.dll/navcancl.htm"
"InPrivate"="res://ieframe.dll/inprivate.htm"
"NavigationCanceled"="res://ieframe.dll/navcancl.htm"
"NavigationFailure"="res://ieframe.dll/navcancl.htm"
"NoAdd-ons"="res://ieframe.dll/noaddon.htm"
"NoAdd-onsInfo"="res://ieframe.dll/noaddoninfo.htm"
"OfflineInformation"="res://ieframe.dll/offcancl.htm"
"PostNotCached"="res://ieframe.dll/repost.htm"
"SecurityRisk"="res://ieframe.dll/securityatrisk.htm"
"Tabs"="res://ieframe.dll/tabswelcome.htm"

**Mininum Windows Version**
Windows XP

**Maximum Windows Version**
Unknown, as the registry values were found on a XP VM running IE8

**Sources and/or information**
This makes it possible to change, for example, the "New Tabs Welcome" page to Google or any other site, it can also change the blank page something that isn't blank.

**Comment by PF94** [comment]
Blank is finished, The other stuff are missing

**Comment by PF94** [comment]
Trivia: This is a month old

**Comment by Craftplacer** [comment]
Are all of them even working?

**Comment by PF94** [comment]
They should.

**Comment by PF94** [comment]
:tada:
