### ISSUE TITLE
How about another file type for the Extensions?

### ISSUE THREAD

**Issue by PF94** [Craftplacer/TweakUtility#30]
Instand of "DLL". it could be... say like "TweakDLL". It'll also make it able to make a easy to use installer.

**Comment by Craftplacer** [comment]
> It'll also make it able to make a easy to use installer.
What do you mean with that?

**Comment by PF94** [comment]
A installer that can install the TweakUtility add-ons easily,

**Comment by Craftplacer** [comment]
That was already the point of having that extension type... You haven't noticed the installer change I made where we added .TUEX (Tweak Utility EXtension)

**Comment by PF94** [comment]
TUEX is a far more catchy name for a file name.

**Comment by PF94** [comment]
Closing this down...
