### ISSUE TITLE
VISUAL C++ Redist all version installer

### ISSUE THREAD

**Issue by AlienFuture** [Craftplacer/TweakUtility#31]
Sup,
I have an idea for TU.

What about an option which is automatically install all Visual C++ Redist package from 2005-2017?
Its useful on older versions I think

**Comment by Craftplacer** [comment]
Where would it needed? Shouldn't applications automatically notify the user about a missing dependency?

**Comment by AlienFuture** [comment]
Anytimes not. And it dont need install VSC++ in app installer just you install them with one click......

**Comment by Craftplacer** [comment]
If you want to you can implement it under Uncategorized.

**Comment by Craftplacer** [comment]
But still don't think it fits the main theme of Tweak Utility, since it's more of a script, not really tweaking anything.

**Comment by PF94** [comment]
I don't think we were meant to be a "all in one windows update" application, these apps already exist

**Comment by AlienFuture** [comment]
C++ != Windows Update.....
