### ISSUE TITLE
TweakUtility on Windows Vista doesn't load any pages.

### ISSUE THREAD

**Issue by chaziz94** [Craftplacer/TweakUtility#40]
**Describe the bug**
No pages loads, thus making TweakUtility useless.

**To Reproduce**
1. Execute TweakUtility
2. Appect the UAC prompt (they're too common in Vista)
3. Get 7 errors about a page not loading.
4. TweakUtility says "Navigate to a page to get started!", yet there is nothing in the sidebar list.

**Expected behavior**
TweakUtility should have loaded all of them.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/45898787/70767910-fee0c300-1d30-11ea-8f36-0d1ab7f86b1c.png)

**Information (please complete the following information):**
 - OS: Windows Vista Ultimate SP2
 - Version: 1.1.00

**Additional context**
I installed Vista like, a few hours ago (as of writing this), i'm starting to install all of my programs (or use alternatives or older versions if the current one doesn't work with Vista), but TweakUtility, mysteriously, broke.

Edit: Remember the dead meme (Creeper, aw man) you added in the build? It doesn't show any error when loading TweakUtility.

**Comment by PF94** [comment]
Also: Some apps are prone to mal-function or even crash on the same copy of Vista.

- Media Center: 1/2 chances of crashing when trying to play a music file
- Blockland v20 (my patched client): crashes when on Kenko's server
- NetBalancer (old version): Doesn't load, throws a C# error i remember seeing a lot on TweakUtility live share sessions.
- Steam (last version that works with Vista): Throws two errors of "Driver query" apps.
- Virtualbox (only happend like once): Clicking status bar while installing a VM for a unrelated project crashed the VM.

**Comment by Craftplacer** [comment]
No exception details.

**Comment by PF94** [comment]
It's not invalid, if you're going to put the invalid label again, I'm going to uninstall TweakUtility from Vista.

I'm not on my Vista PC right now, I'm going to put this on hold.

**Comment by Craftplacer** [comment]
we didn't have a gray "missing details" label, but still, I can't fix something on a system I don't have and not providing the errors spit out by my code where and why it crashed isn't helping me.

**Comment by PF94** [comment]
oh right.

**Comment by PF94** [comment]
![image](https://user-images.githubusercontent.com/45898787/71564290-6b1b3080-2a6c-11ea-865a-73e66bc75b8f.png)
![image](https://user-images.githubusercontent.com/45898787/71564291-6eaeb780-2a6c-11ea-8888-35be7499c9e3.png)
![image](https://user-images.githubusercontent.com/45898787/71564292-71a9a800-2a6c-11ea-840f-552f83b5d140.png)
![image](https://user-images.githubusercontent.com/45898787/71564294-7706f280-2a6c-11ea-9943-31ac21c3ecf0.png)
![image](https://user-images.githubusercontent.com/45898787/71564295-7a01e300-2a6c-11ea-9b01-14daabb5c078.png)
![image](https://user-images.githubusercontent.com/45898787/71564296-7d956a00-2a6c-11ea-82b9-29d1668ab132.png)

**Comment by Craftplacer** [comment]
Okay this narrows down where the exception happened but this still needs to be debugged.

**Comment by PF94** [comment]
well, i am on vista, which means i can't develop tweakutility.

**Comment by chaziz94** [comment]
for the super slim chances of tweakutility getting revived, we shouldn't bother with XP/Vista support at all.

**Comment by Craftplacer** [comment]
Well true since the chances of it being used are slim, this would mean the project can be targetting .NET (Core) 5/6 then

**Comment by chaziz94** [comment]
i would still support windows 7, but vista/xp support is out of the table.

in early-2021 we planned on just rewriting the code, so this could be the perfect chance.
