### ISSUE TITLE
Icons for pages

### ISSUE THREAD

**Issue by Craftplacer** [Craftplacer/TweakUtility#6]
**Is your feature request related to a problem? Please describe.**
Not related.

**Describe the solution you'd like**
Icons displayed in the content view and sidebar of the application.

**Describe alternatives you've considered**

**Additional context**
Either, Silk Icons, Windows 7, Windows XP or icons retrieved from system.

**Comment by PF94** [comment]
I'd prob prefer Silk, as my ideas for the wrench icon came from Silk.
